<!docktype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>User Profile</title>
</head>
<body>
<h1>Welcome ${userName}!</h1>

<a href="/users/${userId}/articles">Show My Articles</a>
<a href="/users/articles">Discover Others' Articles</a>
</body>
</html>